export const APPLY_COUNTRIES = [
  { value: "AE", labelKey: "journalistRequest.countries.AE" },
  { value: "SA", labelKey: "journalistRequest.countries.SA" },
  { value: "EG", labelKey: "journalistRequest.countries.EG" },
  { value: "JO", labelKey: "journalistRequest.countries.JO" },
  { value: "LB", labelKey: "journalistRequest.countries.LB" },
  { value: "IQ", labelKey: "journalistRequest.countries.IQ" },
  { value: "SY", labelKey: "journalistRequest.countries.SY" },
  { value: "PS", labelKey: "journalistRequest.countries.PS" },
  { value: "MA", labelKey: "journalistRequest.countries.MA" },
  { value: "TN", labelKey: "journalistRequest.countries.TN" },
  { value: "DZ", labelKey: "journalistRequest.countries.DZ" },
  { value: "LY", labelKey: "journalistRequest.countries.LY" },
  { value: "SD", labelKey: "journalistRequest.countries.SD" },
  { value: "YE", labelKey: "journalistRequest.countries.YE" },
  { value: "OM", labelKey: "journalistRequest.countries.OM" },
  { value: "KW", labelKey: "journalistRequest.countries.KW" },
  { value: "QA", labelKey: "journalistRequest.countries.QA" },
  { value: "BH", labelKey: "journalistRequest.countries.BH" },
  { value: "OTHER", labelKey: "journalistRequest.countries.OTHER" },
] as const;
